### ISSUE TITLE
Passing params between pages (Client only)

### ISSUE THREAD

**Issue by BelfastMarsh** [CSOIreland/Client-API-Library#7]
Passing params between pages.

Hi, 
We're using just the Client API in Collect External for an eForms library page, and we need to be able to pass a parameter from one page to the next so it can be used to display particular content on the next page. 

I hacked about with a local copy of api.library.js removing the lines which empty the api.content.params variable in the api.content.load function, and adding another function to enable emptying the variable once the content has been grabbed. This way the params variable remains accessible on the next page. I feel this is a little too hacky, however, is there an official/better way of doing this?

I've included my hacky version for you to look at.

thanks
Peter Marsh
Collect External
[api.library.pm.zip](https://github.com/CSOIreland/Client-API-Library/files/10675280/api.library.pm.zip)

**Comment by lanesCSO** [comment]
@BelfastMarsh for the api.content.getParam to work it must be before the $(document).ready function call to be guaranteed to work.

see bug report https://github.com/CSOIreland/Client-API-Library/issues/4
